update build deb

diff --git a/build b/build
--- a/build
+++ b/build
@@ -32,51 +32,50 @@
 #################################################################################
 
 check_make_ok() {
-  if [ $? != 0 ]; then
-    echo ""
-    echo "Make Failed..."
-    echo "Please check the messages and fix any problems. If you're still stuck,"
-    echo "then please email all the output and as many details as you can to"
-    echo "  projects@drogon.net"
-    echo ""
-    exit 1
-  fi
+	if [ $? != 0 ]; then
+		echo ""
+		echo "Make Failed..."
+		echo "Please check the messages and fix any problems. If you're still stuck,"
+		echo "then please email all the output and as many details as you can to"
+		echo "  projects@drogon.net"
+		echo ""
+		exit 1
+	fi
 }
 
-select_boards()
-{
-    local cnt=0
-    local choice
-    local call=${1}
+select_boards() {
+	local cnt=0
+	local choice
+	local call=${1}
 
-    boards=("clockworkpi-a04" "clockworkpi-a06" )
+	boards=("clockworkpi-a04" "clockworkpi-a06")
 
-    if [[ -f /etc/armbian-release ]]; then 
+	if [[ -f /etc/armbian-release ]]; then
 
-	source /etc/armbian-release
+		source /etc/armbian-release
 
-    else
+	else
 
-	printf "All available boards:\n"
-    	for var in ${boards[@]} ; do
-       		 printf "%4d. %s\n" $cnt ${boards[$cnt]}
-			((cnt+=1))
-    	done
+		printf "All available boards:\n"
+		for var in ${boards[@]}; do
+			printf "%4d. %s\n" $cnt ${boards[$cnt]}
+			((cnt += 1))
+		done
 
-    	while true ; do
-        	read -p "Choice: " choice
-        	if [ -z "${choice}" ] ; then
-            		continue
-        	fi
-        	if [ -z "${choice//[0-9]/}" ] ; then
-            		if [ $choice -ge 0 -a $choice -lt $cnt ] ; then
-				export BOARD="${boards[$choice]}"
-				break
-            		fi
-        	fi
-        	printf "Invalid input ...\n"
-    	done
-    fi
+		while true; do
+			read -p "Choice: " choice
+			if [ -z "${choice}" ]; then
+				continue
+			fi
+			if [ -z "${choice//[0-9]/}" ]; then
+				if [ $choice -ge 0 -a $choice -lt $cnt ]; then
+					export BOARD="${boards[$choice]}"
+					break
+				fi
+			fi
+			printf "Invalid input ...\n"
+		done
+	fi
 
 	[[ $BOARD == clockworkpi-a04 ]] && BOARD=clockworkpi-a04-h6
 	[[ $BOARD == clockworkpi-a06 ]] && BOARD=clockworkpi-a06-rk3399
@@ -87,70 +86,84 @@ select_boards()
 sudo=${WIRINGPI_SUDO-sudo}
 
 if [ x$1 = "xclean" ]; then
-  cd wiringPi
-  echo -n "wiringPi:   "	; make clean
-  cd ../devLib
-  echo -n "DevLib:     "	; make clean
-  cd ../gpio
-  echo -n "gpio:       "	; make clean
-  cd ../examples
-  echo -n "Examples:   "	; make clean
-  cd Gertboard
-  echo -n "Gertboard:  "	; make clean
-  cd ../PiFace
-  echo -n "PiFace:     "	; make clean
-  cd ../q2w
-  echo -n "Quick2Wire: "	; make clean
-  cd ../PiGlow
-  echo -n "PiGlow:     "	; make clean
-  cd ../scrollPhat
-  echo -n "scrollPhat: "	; make clean
-  cd ../..
-  echo -n "Deb: " ; rm  -f debian-template/wiringpi*.deb
-  echo
-  exit
+	cd wiringPi
+	echo -n "wiringPi:   "
+	make clean
+	cd ../devLib
+	echo -n "DevLib:     "
+	make clean
+	cd ../gpio
+	echo -n "gpio:       "
+	make clean
+	cd ../examples
+	echo -n "Examples:   "
+	make clean
+	cd Gertboard
+	echo -n "Gertboard:  "
+	make clean
+	cd ../PiFace
+	echo -n "PiFace:     "
+	make clean
+	cd ../q2w
+	echo -n "Quick2Wire: "
+	make clean
+	cd ../PiGlow
+	echo -n "PiGlow:     "
+	make clean
+	cd ../scrollPhat
+	echo -n "scrollPhat: "
+	make clean
+	cd ../..
+	echo -n "Deb: "
+	rm -f debian-template/wiringpi*.deb
+	echo
+	exit
 fi
 
 if [ x$1 = "xuninstall" ]; then
-  cd wiringPi
-  echo -n "wiringPi: " ; $sudo make uninstall
-  cd ../devLib
-  echo -n "DevLib:   " ; $sudo make uninstall
-  cd ../gpio
-  echo -n "gpio:     " ; $sudo make uninstall
-  exit
+	cd wiringPi
+	echo -n "wiringPi: "
+	$sudo make uninstall
+	cd ../devLib
+	echo -n "DevLib:   "
+	$sudo make uninstall
+	cd ../gpio
+	echo -n "gpio:     "
+	$sudo make uninstall
+	exit
 fi
 
 # Only if you know what you're doing!
 
 if [ x$1 = "xdebian" ]; then
-  here=`pwd`
-  cd debian-template/wiringPi
-  rm -rf usr
-  cd $here/wiringPi
-  make install-deb
-  cd $here/devLib
-  make install-deb INCLUDE='-I. -I../wiringPi'
-  cd $here/gpio
-  make install-deb INCLUDE='-I../wiringPi -I../devLib' LDFLAGS=-L../debian-template/wiringPi/usr/lib
-  cd $here/debian-template
-  fakeroot dpkg-deb --build wiringPi
-  mv wiringPi.deb  wiringpi-`cat $here/VERSION`-1.deb
-  exit
+	here=$(pwd)
+	deb_destdir=${here}/debian-template/wiringPi
+	cd debian-template/wiringPi
+	rm -rf usr
+	cd $here/wiringPi
+	make install-deb DEB_DESTDIR=${deb_destdir}
+	cd $here/devLib
+	make install-deb INCLUDE='-I. -I../wiringPi' DEB_DESTDIR=${deb_destdir}
+	cd $here/gpio
+	make install-deb INCLUDE='-I../wiringPi -I../devLib' LDFLAGS=-L../debian-template/wiringPi/usr/lib DEB_DESTDIR=${deb_destdir}
+	cd $here/debian-template
+	fakeroot dpkg-deb --build wiringPi
+	mv wiringPi.deb wiringpi-$(cat $here/VERSION)-1.deb
+	exit
 fi
 
 if [ x$1 != "x" ]; then
-  echo "Usage: $0 [clean | uninstall]"
-  exit 1
+	echo "Usage: $0 [clean | uninstall]"
+	exit 1
 fi
 
-  select_boards
+select_boards
 
-  echo "wiringPi Build script"
-  echo "====================="
-  echo
+echo "wiringPi Build script"
+echo "====================="
+echo
 
-  hardware=`fgrep Hardware /proc/cpuinfo | head -1 | awk '{ print $3 }'`
+hardware=$(fgrep Hardware /proc/cpuinfo | head -1 | awk '{ print $3 }')
 
 #  if [ x$hardware != "xBCM2708" ]; then
 #    echo ""
@@ -167,44 +180,43 @@ fi
 #    exit 1
 #  fi
 
+echo
+echo "WiringPi Library"
+cd wiringPi
+$sudo make uninstall
+if [ x$1 = "xstatic" ]; then
+	make -j5 static
+	check_make_ok
+	$sudo make install-static
+else
+	make -j5
+	check_make_ok
+	$sudo make install
+fi
+check_make_ok
 
-  echo
-  echo "WiringPi Library"
-  cd wiringPi
-  $sudo make uninstall
-  if [ x$1 = "xstatic" ]; then
-    make -j5 static
-    check_make_ok
-    $sudo make install-static
-  else
-    make -j5
-    check_make_ok
-    $sudo make install
-  fi
-  check_make_ok
+echo
+echo "WiringPi Devices Library"
+cd ../devLib
+$sudo make uninstall
+if [ x$1 = "xstatic" ]; then
+	make -j5 static
+	check_make_ok
+	$sudo make install-static
+else
+	make -j5
+	check_make_ok
+	$sudo make install
+fi
+check_make_ok
 
-  echo
-  echo "WiringPi Devices Library"
-  cd ../devLib
-  $sudo make uninstall
-  if [ x$1 = "xstatic" ]; then
-    make -j5 static
-    check_make_ok
-    $sudo make install-static
-  else
-    make -j5
-    check_make_ok
-    $sudo make install
-  fi
-  check_make_ok
-
-  echo
-  echo "GPIO Utility"
-  cd ../gpio
-  make -j5
-  check_make_ok
-  $sudo make install
-  check_make_ok
+echo
+echo "GPIO Utility"
+cd ../gpio
+make -j5
+check_make_ok
+$sudo make install
+check_make_ok
 
 # echo
 # echo "wiringPi Daemon"
